---

# Ansible config
ansible_connection: local

# Homebrew taps (repos)
homebrew_taps:
  - versent/homebrew-taps

# Homebrew formulae (packages)
homebrew_formulae:
  - bmon
  - composer
  - coreutils
  - docker-machine
  - docker-machine-driver-xhyve
  - git
  - gnu-tar
  - gnupg
  - go
  - gradle
  - groovy
  - jq
  - kubernetes-cli
  - kubernetes-helm
  - maven
  - minikube
  - node
  - openjdk
  - packer
  - pass
  - podman
  - versent/taps/saml2aws
  - sshuttle
  - terraform
  - tree
  - watch
  - wget

# Python packages
pip_packages:
  - setuptools      # Version bundled with Mac OS is very old
  - six             # Version bundled with Mac OS is very old
  - ansible         # Ansible docs recommend installation via pip
  - ansible-lint
  - awscli
  - cfn-lint
  - cfn_flip
  - docker
  - pylint
  - pyOpenSSL       # Required by awscli, per https://github.com/aws/aws-cli/issues/4708
  - PyYAML
  - shyaml
  - virtualenv
