---

- hosts: all
  tasks:
    - include_tasks: tasks/01-configure-os.yml
    - include_tasks: tasks/02-configure-packages.yml
    - include_tasks: tasks/03-configure-apps.yml
    - include_tasks: tasks/04-configure-demos.yml
