---

- hosts: all
  tasks:

# OS packages

  - name: add homebrew taps (repos)
    homebrew_tap:
      name: "{{ item }}"
      state: present
    loop: "{{ homebrew_taps }}"

  - name: install homebrew formulae (packages)
    package:
      name: "{{ item }}"
      state: latest
    loop: "{{ homebrew_formulae }}"

# Python packages

  - name: download pip installer script
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py

  - name: install pip
    command: python /tmp/get-pip.py --user

  - name: install python packages
    pip:
      name: "{{ item }}"
      extra_args: "--upgrade --user"
    loop: "{{ pip_packages }}"

# Dot files

  - name: template .bash_profile
    template:
      src: templates/bash/bash_profile
      dest: $HOME/.bash_profile
      mode: 0644

  - name: template .gitconfig
    template:
      src: templates/git/gitconfig
      dest: $HOME/.gitconfig
      mode: 0644

  - name: template .saml2aws
    template:
      src: templates/saml2aws/saml2aws
      dest: $HOME/.saml2aws
      mode: 0644

  - name: template vscode settings.json
    template:
      src: templates/vscode/settings.json
      dest: "$HOME/Library/Application Support/Code/User/settings.json"
      mode: 0644

  - name: template vscode tasks.json
    template:
      src: templates/vscode/tasks.json
      dest: "$HOME/Library/Application Support/Code/User/tasks.json"
      mode: 0644

  - name: template .zshrc
    template:
      src: templates/zsh/zshrc
      dest: $HOME/.zshrc
      mode: 0644
