---

# Configure shells

  - name: template .bash_profile
    template:
      src: templates/bash/bash_profile
      dest: $HOME/.bash_profile
      mode: 0644

  - name: template .zshrc
    template:
      src: templates/zsh/zshrc.j2
      dest: $HOME/.zshrc
      mode: 0644
