---

# Configure macOS user defaults, same as "defaults write ..."

  - name: configure defaults
    osx_defaults:
      domain: "{{ item.domain }}"
      key: "{{ item.key }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      state: present
    loop: "{{ macos_defaults }}"

# Relaunch processes to apply macOS user defaults

  - name: relaunch processes (to apply defaults)
    command: "killall {{ item }}"
    loop: "{{ macos_processes_to_relaunch }}"


# Configure shells

  - name: template .bash_profile
    template:
      src: templates/bash/bash_profile
      dest: $HOME/.bash_profile
      mode: 0644

  - name: install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: $HOME/.oh-my-zsh/

  # Template .zshrc *after* installtion of oh-my-zsh above, since first-time setup of
  # oh-my-zsh backs up .zshrc and writes a new one
  - name: template .zshrc
    template:
      src: templates/zsh/zshrc.j2
      dest: $HOME/.zshrc
      mode: 0644
