# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  aws
  colored-man-pages
  git
  osx
  sudo
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#######################################################

# My customisations


# Source bash profile (only for configuration added by installers)
source $HOME/.bash_profile


# Remove username@hostname from prompt (when logged in as myself on localhost)
DEFAULT_USER=$USER


# Java home
export JAVA_HOME=/usr/local/opt/openjdk

# Groovy home
export GROOVY_HOME=/usr/local/opt/groovy/libexec


# Java bin path
export PATH="$JAVA_HOME/bin:$PATH"

# Go path
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# MacPorts bin path
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# Python site packages path
export PATH="$HOME/Library/Python/3.9/bin:$PATH"

# Sonar bin path
export PATH="/opt/sonar-scanner-3.2.0.1227-macosx/bin:$PATH"

# Visual Studio Code path
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"


# My bin path
export PATH="$HOME/bin:$PATH"

# AWS Login for Mercer
#[ -f $HOME/bin/mercer-aws-login.sh ] && . $HOME/bin/mercer-aws-login.sh


# Aliases
alias git-ping='cd ~/repos/github/pingidentity/'
alias git-tu='cd ~/repos/customers/transurban/'
alias git-versent='cd ~/repos/github/versent/'
alias git-vix='cd ~/repos/customers/vix/codecommit/'

# Workaround for the following ansible bug on Mac OS High Sierra (10.13):
# https://github.com/ansible/ansible/issues/32499
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES


# Functions
function docker() {
  case $* in
    images* )
      shift 1
      command docker images "$@" | head -1
      command docker images "$@" | tail +2 | sort
      ;;
    * )
      command docker "$@"
      ;;
  esac
}

fuction git() {
  case $* in
    push* )
      shift 1
      command git push -u "$@"
      ;;
    * )
      command git "$@"
      ;;
  esac
}

function tu-proxy-status() {
    echo http_proxy = $http_proxy
    echo HTTP_PROXY = $HTTP_PROXY

    echo https_proxy = $https_proxy
    echo HTTPS_PROXY = $HTTPS_PROXY

    echo no_proxy = $no_proxy
    echo NO_PROXY = $NO_PROXY
}

function tu-proxy-enable() {
    # Transurban on-prem HTTP proxy
    export http_proxy=http://proxy-au.transurban.com.au:9090
    export HTTP_PROXY=http://proxy-au.transurban.com.au:9090

    # Transurban on-prem HTTPS proxy
    export https_proxy=http://proxy-au.transurban.com.au:9090
    export HTTPS_PROXY=http://proxy-au.transurban.com.au:9090

    # Bypass proxy
    export no_proxy=localhost
    export NO_PROXY=localhost

    tu-proxy-status
}

function tu-proxy-disable() {
    unset http_proxy HTTP_PROXY
    unset https_proxy HTTPS_PROXY
    unset no_proxy NO_PROXY

    tu-proxy-status
}
